
version: '3.8'
services:
  web:
    build: .
    ports:
      - "5000:5000"
    environment:
      - DATABASE_URL=postgresql://postgres:your_secure_password@db:5432/license_manager
      - SESSION_SECRET=your_secure_session_secret
    depends_on:
      - db
  
  db:
    image: postgres:13
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=your_secure_password
      - POSTGRES_DB=license_manager
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
